format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
${custom.git_host}\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$cmd_duration\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[cmd_duration]
show_notifications = true
min_time_to_notify = 60_000
min_time = 1  # Show command duration over 10,000 milliseconds (=10 sec)
format = '\[[⏱ $duration]($style)\]'
style = 'yellow'

##################################################################
# ## git configuraton
# [git_branch]
# style = "bg:#394260"
# format = "[$symbol$branch]($style)"
# symbol = " "

[git_state]
style = "bg:#394260"
format = '\(:[$state( $progress_current/$progress_total)]($style)\)'
cherry_pick = "[🍒 PICKING](bold red)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
#format = '(:[$all_status$ahead_behind]($style))'
conflicted = '\[⚔️ [$count](fg:#769ff0 bg:#394260)\]'
ahead = '\[[﯁💨 ](bright-blue)[$count](fg:#769ff0 bg:#394260)\]'
behind = '\[[﮾🐢 ](white)[$count](fg:#769ff0 bg:#394260)\]'
diverged = '\[[ ](purple)|[ ﯁ ](bright-blue)[$ahead_count](fg:#769ff0 bg:#394260)[ ﮾ ](white)[$behind_count](bright-white)\]'
untracked = '\[🛤️ [$count](fg:#769ff0 bg:#394260)\]'
stashed = '\[[📦](yellow) [$count](fg:#769ff0 bg:#394260)\]'
modified = '\[[ ](bright-yellow)[$count](fg:#769ff0 bg:#394260)\]'
staged = '\[[🗃️ ](fg:#769ff0 bg:#394260)[$count](fg:#769ff0 bg:#394260)\]'
renamed = '\[[📛 ](bright-cyan) [$count](fg:#769ff0 bg:#394260)\]'
deleted = '\[ [$count](fg:#769ff0 bg:#394260)\]'

#################################################################
## Custom scripts
# git
[custom.git_host]
command = "~/.config/starship/scripts/git_host.sh"
directories = [".git"]
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash","--norc","--noprofile"]
style = "bg:#394260"
format = "[$output]($style)"

[custom.git_scope]
disabled = true
command = "~/.config/starship/scripts/git_scope.sh"
description = 'The currently configured Git user.{email,name}'
format = '$output '
style = "bg:#394260"
when = 'git rev-parse --is-inside-work-tree'

# ssh
[custom.ssh_no_keys]
#disabled = true
description = "SSH missing keys"
when = "ssh-add -l | grep -q 'no identities'"
command = "echo 🚫"
format = '\[$symbol[$output]($style)\]'
shell = ["bash", "--noprofile", "--norc"]
symbol = "🔑"
style = "bold fg:red"

[custom.ssh_keys]
#disabled = true
description = "SSH key count"
when = "ssh-add -l | grep -v -q 'no identities'"
command = "ssh-add -l | grep -v 'no identities' | wc -l"
format = '\[$symbol[$output]($style)\]'
shell = ["bash", "--noprofile", "--norc"]
symbol = "🔑"
style = "bold fg:green"



[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

